In [7]:
import sys
import os
import warnings
from zoneinfo import ZoneInfo
from datetime import datetime, timezone, timedelta
from pathlib import Path
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns
import pytz
import json
from pandas import Timestamp
from statsmodels.tsa.stattools import adfuller, kpss, acf, pacf
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.stats.diagnostic import acorr_ljungbox
from statsmodels.tsa.arima.model import ARIMA
from sklearn.model_selection import TimeSeriesSplit
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import r2_score
from scipy.stats import norm

current_dir = Path.cwd()
parent_dir = current_dir.parent
sys.path.insert(0, str(parent_dir))
from lib import *

MODEL_PATH=parent_dir / 'models' 
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 1000)

In [8]:
lookback_minutes = 60
crypto_at = datetime(2026, 5, 4, 4, 30, 0, tzinfo=ZoneInfo('America/Chicago'))
series = 'KXBTC15M'
ticker = 'KXBTC15M-26MAY040515-15'
series, event_dt = parse_kalshi_15m_event_ticker(ticker)
df_api = get_market_data_from_api(series, crypto_at, lookback_minutes)
df_api = df_api.set_index('datetime')
df_api.index = df_api.index.tz_convert('America/Chicago')
df_api.sort_index(inplace=True)
print(f"df_api: {len(df_api)}")
df_api

df_api: 60

,ticker,volume_fp,open_interest_fp,floor_strike,end_period_ts,yes_ask_open_dollar,yes_ask_high_dollar,yes_ask_low_dollar,yes_ask_close_dollar,yes_bid_open_dollar,yes_bid_high_dollar,yes_bid_low_dollar,yes_bid_close_dollar,no_ask_open_dollar,no_ask_high_dollar,no_ask_low_dollar,no_ask_close_dollar,no_bid_open_dollar,no_bid_high_dollar,no_bid_low_dollar,no_bid_close_dollar
datetime,,,,,,,,,,,,,,,,,,,,,
2026-05-04 03:16:00-05:00,KXBTC15M-26MAY040430-30,10036.16,7219.16,79772.80,1777882560,0.999,0.999,0.490,0.510,0.000,0.590,0.000,0.500,1.000,0.410,1.000,0.500,0.001,0.001,0.510,0.490
2026-05-04 03:17:00-05:00,KXBTC15M-26MAY040430-30,15070.96,13553.00,79772.80,1777882620,0.510,0.510,0.280,0.290,0.500,0.500,0.270,0.270,0.500,0.500,0.730,0.730,0.490,0.490,0.720,0.710
2026-05-04 03:18:00-05:00,KXBTC15M-26MAY040430-30,6651.52,16715.65,79772.80,1777882680,0.290,0.300,0.230,0.250,0.270,0.290,0.210,0.240,0.730,0.710,0.790,0.760,0.710,0.700,0.770,0.750
2026-05-04 03:19:00-05:00,KXBTC15M-26MAY040430-30,14076.34,21052.40,79772.80,1777882740,0.250,0.440,0.250,0.390,0.240,0.430,0.240,0.380,0.760,0.570,0.760,0.620,0.750,0.560,0.750,0.610
2026-05-04 03:20:00-05:00,KXBTC15M-26MAY040430-30,20702.41,23347.74,79772.80,1777882800,0.390,0.500,0.350,0.450,0.380,0.490,0.330,0.440,0.620,0.510,0.670,0.560,0.610,0.500,0.650,0.550
2026-05-04 03:21:00-05:00,KXBTC15M-26MAY040430-30,16702.91,24413.49,79772.80,1777882860,0.450,0.500,0.300,0.330,0.440,0.490,0.290,0.320,0.560,0.510,0.710,0.680,0.550,0.500,0.700,0.670
2026-05-04 03:22:00-05:00,KXBTC15M-26MAY040430-30,8835.01,24075.70,79772.80,1777882920,0.330,0.410,0.220,0.220,0.320,0.400,0.190,0.210,0.680,0.600,0.810,0.790,0.670,0.590,0.780,0.780
2026-05-04 03:23:00-05:00,KXBTC15M-26MAY040430-30,15701.50,29679.74,79772.80,1777882980,0.220,0.220,0.048,0.058,0.210,0.210,0.043,0.052,0.790,0.790,0.957,0.948,0.780,0.780,0.952,0.942
2026-05-04 03:24:00-05:00,KXBTC15M-26MAY040430-30,23026.13,38171.43,79772.80,1777883040,0.058,0.070,0.018,0.028,0.052,0.056,0.014,0.019,0.948,0.944,0.986,0.981,0.942,0.930,0.982,0.972
2026-05-04 03:25:00-05:00,KXBTC15M-26MAY040430-30,15042.64,47767.83,79772.80,1777883100,0.028,0.055,0.028,0.048,0.017,0.049,0.017,0.042,0.983,0.951,0.983,0.958,0.972,0.945,0.972,0.952
2026-05-04 03:26:00-05:00,KXBTC15M-26MAY040430-30,4157.37,49640.19,79772.80,1777883160,0.048,0.048,0.015,0.016,0.042,0.042,0.013,0.013,0.958,0.958,0.987,0.987,0.952,0.952,0.985,0.984
2026-05-04 03:27:00-05:00,KXBTC15M-26MAY040430-30,11278.98,56061.37,79772.80,1777883220,0.016,0.033,0.011,0.017,0.013,0.029,0.010,0.013,0.987,0.971,0.990,0.987,0.984,0.967,0.989,0.983
2026-05-04 03:28:00-05:00,KXBTC15M-26MAY040430-30,8315.28,61285.79,79772.80,1777883280,0.017,0.018,0.006,0.007,0.013,0.015,0.002,0.006,0.987,0.985,0.998,0.994,0.983,0.982,0.994,0.993
2026-05-04 03:29:00-05:00,KXBTC15M-26MAY040430-30,5935.44,63310.53,79772.80,1777883340,0.007,0.018,0.003,0.003,0.006,0.016,0.002,0.002,0.994,0.984,0.998,0.998,0.993,0.982,0.997,0.997
2026-05-04 03:30:00-05:00,KXBTC15M-26MAY040430-30,8133.60,68421.75,79772.80,1777883400,0.003,0.010,0.001,0.001,0.002,0.004,0.000,0.000,0.998,0.996,1.000,1.000,0.997,0.990,0.999,0.999
2026-05-04 03:31:00-05:00,KXBTC15M-26MAY040445-45,15994.25,10766.75,79729.31,1777883460,1.000,1.000,0.350,0.380,0.160,0.540,0.160,0.370,0.840,0.460,0.840,0.630,0.000,0.000,0.650,0.620
2026-05-04 03:32:00-05:00,KXBTC15M-26MAY040445-45,18754.94,17904.54,79729.31,1777883520,0.380,0.610,0.350,0.590,0.370,0.600,0.330,0.570,0.630,0.400,0.670,0.430,0.620,0.390,0.650,0.410
2026-05-04 03:33:00-05:00,KXBTC15M-26MAY040445-45,14202.81,17109.13,79729.31,1777883580,0.590,0.660,0.500,0.520,0.570,0.650,0.490,0.510,0.430,0.350,0.510,0.490,0.410,0.340,0.500,0.480
2026-05-04 03:34:00-05:00,KXBTC15M-26MAY040445-45,10222.33,18423.04,79729.31,1777883640,0.520,0.540,0.440,0.460,0.510,0.530,0.420,0.450,0.490,0.470,0.580,0.550,0.480,0.460,0.560,0.540
2026-05-04 03:35:00-05:00,KXBTC15M-26MAY040445-45,12562.42,19702.26,79729.31,1777883700,0.460,0.480,0.280,0.340,0.450,0.460,0.270,0.330,0.550,0.540,0.730,0.670,0.540,0.520,0.720,0.660
2026-05-04 03:36:00-05:00,KXBTC15M-26MAY040445-45,9006.11,18353.20,79729.31,1777883760,0.340,0.550,0.320,0.530,0.330,0.540,0.310,0.520,0.670,0.460,0.690,0.480,0.660,0.450,0.680,0.470
2026-05-04 03:37:00-05:00,KXBTC15M-26MAY040445-45,7907.03,21956.45,79729.31,1777883820,0.530,0.530,0.270,0.280,0.520,0.520,0.250,0.260,0.480,0.480,0.750,0.740,0.470,0.470,0.730,0.720
2026-05-04 03:38:00-05:00,KXBTC15M-26MAY040445-45,6970.09,25282.83,79729.31,1777883880,0.280,0.320,0.260,0.320,0.260,0.310,0.250,0.310,0.740,0.690,0.750,0.690,0.720,0.680,0.740,0.680
2026-05-04 03:39:00-05:00,KXBTC15M-26MAY040445-45,9339.29,25729.82,79729.31,1777883940,0.320,0.520,0.310,0.420,0.310,0.460,0.300,0.410,0.690,0.540,0.700,0.590,0.680,0.480,0.690,0.580
2026-05-04 03:40:00-05:00,KXBTC15M-26MAY040445-45,16715.32,26799.88,79729.31,1777884000,0.420,0.590,0.380,0.390,0.410,0.570,0.360,0.380,0.590,0.430,0.640,0.620,0.580,0.410,0.620,0.610
2026-05-04 03:41:00-05:00,KXBTC15M-26MAY040445-45,12885.39,27555.96,79729.31,1777884060,0.390,0.570,0.350,0.530,0.380,0.550,0.340,0.520,0.620,0.450,0.660,0.480,0.610,0.430,0.650,0.470
2026-05-04 03:42:00-05:00,KXBTC15M-26MAY040445-45,18260.83,26817.03,79729.31,1777884120,0.530,0.620,0.370,0.620,0.520,0.610,0.350,0.600,0.480,0.390,0.650,0.400,0.470,0.380,0.630,0.380
2026-05-04 03:43:00-05:00,KXBTC15M-26MAY040445-45,30373.24,26371.92,79729.31,1777884180,0.620,0.810,0.470,0.720,0.600,0.790,0.460,0.700,0.400,0.210,0.540,0.300,0.380,0.190,0.530,0.280
2026-05-04 03:44:00-05:00,KXBTC15M-26MAY040445-45,39392.08,26175.25,79729.31,1777884240,0.710,0.720,0.032,0.050,0.700,0.700,0.028,0.047,0.300,0.300,0.972,0.953,0.290,0.280,0.968,0.950
2026-05-04 03:45:00-05:00,KXBTC15M-26MAY040445-45,21278.16,37627.99,79729.31,1777884300,0.048,0.060,0.001,0.001,0.047,0.047,0.000,0.000,0.953,0.953,1.000,1.000,0.952,0.940,0.999,0.999
2026-05-04 03:46:00-05:00,KXBTC15M-26MAY040500-00,8712.29,5156.25,79701.38,1777884360,1.000,1.000,0.480,0.510,0.160,0.550,0.160,0.500,0.840,0.450,0.840,0.500,0.000,0.000,0.520,0.490
2026-05-04 03:47:00-05:00,KXBTC15M-26MAY040500-00,7597.34,9307.74,79701.38,1777884420,0.510,0.570,0.500,0.530,0.500,0.560,0.480,0.510,0.500,0.440,0.520,0.490,0.490,0.430,0.500,0.470
2026-05-04 03:48:00-05:00,KXBTC15M-26MAY040500-00,14224.56,14050.37,79701.38,1777884480,0.530,0.540,0.400,0.480,0.510,0.530,0.390,0.470,0.490,0.470,0.610,0.530,0.470,0.460,0.600,0.520
2026-05-04 03:49:00-05:00,KXBTC15M-26MAY040500-00,15996.73,17669.07,79701.38,1777884540,0.480,0.490,0.270,0.290,0.470,0.480,0.250,0.280,0.530,0.520,0.750,0.720,0.520,0.510,0.730,0.710
2026-05-04 03:50:00-05:00,KXBTC15M-26MAY040500-00,12768.52,19106.61,79701.38,1777884600,0.290,0.480,0.290,0.430,0.280,0.460,0.270,0.410,0.720,0.540,0.730,0.590,0.710,0.520,0.710,0.570
2026-05-04 03:51:00-05:00,KXBTC15M-26MAY040500-00,9899.82,23481.69,79701.38,1777884660,0.430,0.430,0.230,0.240,0.410,0.410,0.220,0.220,0.590,0.590,0.780,0.780,0.570,0.570,0.770,0.760
2026-05-04 03:52:00-05:00,KXBTC15M-26MAY040500-00,10185.44,28745.92,79701.38,1777884720,0.240,0.280,0.082,0.088,0.220,0.260,0.076,0.084,0.780,0.740,0.924,0.916,0.760,0.720,0.918,0.912
2026-05-04 03:53:00-05:00,KXBTC15M-26MAY040500-00,12437.12,30144.28,79701.38,1777884780,0.088,0.240,0.071,0.230,0.084,0.220,0.070,0.220,0.916,0.780,0.930,0.780,0.912,0.760,0.929,0.770
2026-05-04 03:54:00-05:00,KXBTC15M-26MAY040500-00,13625.96,32348.63,79701.38,1777884840,0.230,0.390,0.200,0.310,0.220,0.380,0.100,0.300,0.780,0.620,0.900,0.700,0.770,0.610,0.800,0.690
2026-05-04 03:55:00-05:00,KXBTC15M-26MAY040500-00,10257.43,31924.14,79701.38,1777884900,0.310,0.530,0.310,0.410,0.300,0.520,0.300,0.400,0.700,0.480,0.700,0.600,0.690,0.470,0.690,0.590
2026-05-04 03:56:00-05:00,KXBTC15M-26MAY040500-00,20688.13,29000.14,79701.38,1777884960,0.410,0.870,0.320,0.870,0.400,0.860,0.300,0.860,0.600,0.140,0.700,0.140,0.590,0.130,0.680,0.130
2026-05-04 03:57:00-05:00,KXBTC15M-26MAY040500-00,14949.70,34533.45,79701.38,1777885020,0.870,0.870,0.750,0.780,0.860,0.860,0.740,0.770,0.140,0.140,0.260,0.230,0.130,0.130,0.250,0.220
2026-05-04 03:58:00-05:00,KXBTC15M-26MAY040500-00,38438.35,42407.64,79701.38,1777885080,0.780,0.970,0.780,0.957,0.770,0.965,0.760,0.952,0.230,0.035,0.240,0.048,0.220,0.030,0.220,0.043
2026-05-04 03:59:00-05:00,KXBTC15M-26MAY040500-00,51947.98,34066.91,79701.38,1777885140,0.957,0.959,0.070,0.380,0.952,0.952,0.068,0.370,0.048,0.048,0.932,0.630,0.043,0.041,0.930,0.620
2026-05-04 04:00:00-05:00,KXBTC15M-26MAY040500-00,87162.46,59152.65,79701.38,1777885200,0.380,0.903,0.006,0.006,0.370,0.840,0.005,0.005,0.630,0.160,0.995,0.995,0.620,0.097,0.994,0.994
2026-05-04 04:01:00-05:00,KXBTC15M-26MAY040515-15,14307.27,11997.07,79700.50,1777885260,0.840,0.840,0.340,0.350,0.000,0.480,0.000,0.340,1.000,0.520,1.000,0.660,0.160,0.160,0.660,0.650
2026-05-04 04:02:00-05:00,KXBTC15M-26MAY040515-15,10891.66,18155.63,79700.50,1777885320,0.350,0.350,0.250,0.340,0.340,0.340,0.240,0.330,0.660,0.660,0.760,0.670,0.650,0.650,0.750,0.660
2026-05-04 04:03:00-05:00,KXBTC15M-26MAY040515-15,17153.31,18710.58,79700.50,1777885380,0.340,0.620,0.340,0.560,0.330,0.610,0.310,0.550,0.670,0.390,0.690,0.450,0.660,0.380,0.660,0.440
2026-05-04 04:04:00-05:00,KXBTC15M-26MAY040515-15,19603.44,20655.01,79700.50,1777885440,0.560,0.760,0.560,0.720,0.550,0.740,0.550,0.700,0.450,0.260,0.450,0.300,0.440,0.240,0.440,0.280
2026-05-04 04:05:00-05:00,KXBTC15M-26MAY040515-15,12361.63,17747.37,79700.50,1777885500,0.720,0.780,0.610,0.650,0.700,0.760,0.600,0.630,0.300,0.240,0.400,0.370,0.280,0.220,0.390,0.350
2026-05-04 04:06:00-05:00,KXBTC15M-26MAY040515-15,11923.27,19172.82,79700.50,1777885560,0.650,0.660,0.490,0.530,0.630,0.650,0.480,0.510,0.370,0.350,0.520,0.490,0.350,0.340,0.510,0.470
2026-05-04 04:07:00-05:00,KXBTC15M-26MAY040515-15,12467.48,17321.64,79700.50,1777885620,0.530,0.580,0.520,0.520,0.510,0.570,0.500,0.510,0.490,0.430,0.500,0.490,0.470,0.420,0.480,0.480
2026-05-04 04:08:00-05:00,KXBTC15M-26MAY040515-15,21726.02,25151.01,79700.50,1777885680,0.520,0.590,0.310,0.480,0.510,0.580,0.300,0.470,0.490,0.420,0.700,0.530,0.480,0.410,0.690,0.520
2026-05-04 04:09:00-05:00,KXBTC15M-26MAY040515-15,10621.89,25858.85,79700.50,1777885740,0.480,0.530,0.370,0.380,0.470,0.510,0.350,0.360,0.530,0.490,0.650,0.640,0.520,0.470,0.630,0.620
2026-05-04 04:10:00-05:00,KXBTC15M-26MAY040515-15,15348.10,30079.56,79700.50,1777885800,0.380,0.460,0.240,0.400,0.360,0.440,0.230,0.390,0.640,0.560,0.770,0.610,0.620,0.540,0.760,0.600
2026-05-04 04:11:00-05:00,KXBTC15M-26MAY040515-15,53803.72,31467.19,79700.50,1777885860,0.400,0.932,0.270,0.880,0.390,0.930,0.250,0.870,0.610,0.070,0.750,0.130,0.600,0.068,0.730,0.120
2026-05-04 04:12:00-05:00,KXBTC15M-26MAY040515-15,23358.10,41808.17,79700.50,1777885920,0.880,0.920,0.860,0.913,0.870,0.913,0.850,0.910,0.130,0.087,0.150,0.090,0.120,0.080,0.140,0.087
2026-05-04 04:13:00-05:00,KXBTC15M-26MAY040515-15,20450.91,50453.46,79700.50,1777885980,0.913,0.914,0.780,0.890,0.910,0.910,0.760,0.880,0.090,0.090,0.240,0.120,0.087,0.086,0.220,0.110
2026-05-04 04:14:00-05:00,KXBTC15M-26MAY040515-15,19215.16,56656.14,79700.50,1777886040,0.890,0.955,0.780,0.913,0.880,0.954,0.770,0.903,0.120,0.046,0.230,0.097,0.110,0.045,0.220,0.087
2026-05-04 04:15:00-05:00,KXBTC15M-26MAY040515-15,28351.11,64758.89,79700.50,1777886100,0.917,1.000,0.850,1.000,0.903,0.999,0.820,0.999,0.097,0.001,0.180,0.001,0.083,0.000,0.150,0.000

In [9]:
df_crypto = get_crypto_past_minutes(series, crypto_at, lookback_minutes)
df_crypto['datetime'] = pd.to_datetime(df_crypto['datetime'])
df_crypto['datetime'] = df_crypto['datetime'].dt.tz_convert('America/Chicago')
df_crypto['datetime'] = df_crypto['datetime'].dt.floor('min')
df_crypto = df_crypto.set_index('datetime')
df_crypto

                               open      high       low     close  tick_count
datetime
2026-05-04 03:31:00-05:00  79729.82  79738.31  79719.64  79720.00          34
2026-05-04 03:32:00-05:00  79722.16  79722.16  79719.70  79719.70           0
2026-05-04 03:33:00-05:00  79744.36  79765.66  79734.89  79742.61          53
2026-05-04 03:34:00-05:00  79739.24  79739.90  79734.67  79739.49          13
2026-05-04 03:35:00-05:00  79728.05  79728.05  79712.82  79712.82          36
2026-05-04 03:36:00-05:00  79680.74  79687.42  79680.74  79687.42           0
2026-05-04 03:37:00-05:00  79729.01  79730.29  79694.30  79697.07          40
2026-05-04 03:38:00-05:00  79699.49  79699.49  79697.64  79697.64           0
2026-05-04 03:39:00-05:00  79696.43  79696.43  79695.66  79695.66           0
2026-05-04 03:40:00-05:00  79705.43  79705.43  79705.43  79705.43           0
2026-05-04 03:41:00-05:00  79726.47  79734.10  79726.47  79734.10           0
2026-05-04 03:42:00-05:00  79713.19  79713.19  79713.19  79713.19           0
2026-05-04 03:43:00-05:00  79729.29  79729.29  79729.29  79729.29           0
2026-05-04 03:44:00-05:00  79731.33  79731.33  79731.33  79731.33           0
2026-05-04 03:45:00-05:00  79707.28  79707.47  79692.70  79702.37          17
2026-05-04 03:46:00-05:00  79700.94  79701.21  79700.94  79701.21           0
2026-05-04 03:47:00-05:00  79700.05  79711.29  79699.58  79704.43          35
2026-05-04 03:48:00-05:00  79704.43  79704.43  79704.02  79704.02           0
2026-05-04 03:49:00-05:00  79698.27  79698.55  79696.97  79696.97           2
2026-05-04 03:50:00-05:00  79658.83  79659.63  79658.83  79659.63           0
2026-05-04 03:51:00-05:00  79683.44  79685.18  79682.57  79683.35           3
2026-05-04 03:52:00-05:00  79656.23  79656.23  79655.71  79655.71           0
2026-05-04 03:53:00-05:00  79616.64  79654.35  79603.95  79642.49          51
2026-05-04 03:54:00-05:00  79641.13  79641.13  79641.13  79641.13           0
2026-05-04 03:55:00-05:00  79676.23  79682.70  79672.56  79682.35           4
2026-05-04 03:56:00-05:00  79691.69  79691.69  79691.69  79691.69           0
2026-05-04 03:57:00-05:00  79746.36  79746.85  79723.00  79725.45          60
2026-05-04 03:58:00-05:00  79726.45  79726.45  79726.45  79726.45           0
2026-05-04 03:59:00-05:00  79743.63  79743.63  79673.38  79673.48          52
2026-05-04 04:00:00-05:00  79697.03  79697.03  79697.03  79697.03           0
2026-05-04 04:01:00-05:00  79692.40  79692.40  79679.63  79682.26           7
2026-05-04 04:02:00-05:00  79656.51  79656.51  79656.19  79656.19           0
2026-05-04 04:03:00-05:00  79656.33  79721.98  79655.05  79716.36          53
2026-05-04 04:04:00-05:00  79709.41  79727.04  79709.41  79726.40          20
2026-05-04 04:05:00-05:00  79754.96  79773.37  79723.18  79730.66          54
2026-05-04 04:06:00-05:00  79730.10  79730.10  79729.41  79729.41           1
2026-05-04 04:07:00-05:00  79706.81  79710.35  79702.07  79707.97          50
2026-05-04 04:08:00-05:00  79705.11  79705.30  79705.11  79705.30           0
2026-05-04 04:09:00-05:00  79690.08  79690.08  79684.96  79684.96           0
2026-05-04 04:10:00-05:00  79683.13  79684.01  79664.05  79675.07          21
2026-05-04 04:11:00-05:00  79675.07  79675.07  79675.07  79675.07           0
2026-05-04 04:12:00-05:00  79748.19  79756.79  79748.19  79756.79           0
2026-05-04 04:13:00-05:00  79757.85  79758.69  79723.08  79737.49          52
2026-05-04 04:14:00-05:00  79735.27  79735.88  79721.08  79723.07           3
2026-05-04 04:15:00-05:00  79715.44  79723.24  79709.14  79715.38          52
2026-05-04 04:16:00-05:00  79711.44  79730.39  79707.85  79727.49          26
2026-05-04 04:17:00-05:00  79726.49  79732.79  79726.49  79729.34          11
2026-05-04 04:18:00-05:00  79724.42  79724.66  79724.42  79724.66           0
2026-05-04 04:19:00-05:00  79727.40  79727.40  79705.09  79715.02          60
2026-05-04 04:20:00-05:00  79715.02  79715.02  79715.02  79715.02           0
2026-05-04 04:21:00-05:00  79709.74  79709.74  79709.74  79709.74           0
2026-05-04 04:22:00-05:00  79730.52  79731.64  79730.45  79731.64           6
2026-05-04 04:23:00-05:00  79707.95  79719.30  79707.55  79709.04          53
2026-05-04 04:24:00-05:00  79709.04  79710.18  79709.04  79710.18           0
2026-05-04 04:25:00-05:00  79701.42  79710.66  79701.42  79709.60          13
2026-05-04 04:26:00-05:00  79701.32  79735.32  79699.36  79735.32          35
2026-05-04 04:27:00-05:00  79743.18  79800.87  79736.09  79799.68          60
2026-05-04 04:28:00-05:00  79799.68  79801.25  79769.58  79793.66           7
2026-05-04 04:29:00-05:00  79760.22  79760.22  79755.75  79755.75           0
2026-05-04 04:30:00-05:00  79751.67  79751.67  79751.67  79751.67           0

In [ ]:
print(f"df_crypto: {len(df_crypto)}")
filter_timestamp = df_crypto[df_crypto.index.minute.isin([0,15,30,45])].index[0]
df_crypto = df_crypto[df_crypto.index >= filter_timestamp]
df_merged = df_crypto.join(df_api, how='left')
df_merged['yes_dist'] = df_merged['close'] - df_merged['floor_strike']
df_merged['log_return'] = np.log(df_merged['close'] / df_merged['close'].shift(1))
df_merged['3m_log_return'] = df_merged['log_return'].rolling(3).std()
df_merged['5m_log_return'] = df_merged['log_return'].rolling(5).std()
df_merged['ma3'] = df_merged['close'].rolling(3).mean()
df_merged['ma5'] = df_merged['close'].rolling(5).mean()
df_merged['ma3_vs_strike'] = (df_merged['ma3'] - df_merged['floor_strike'])/df_merged['floor_strike'] * 100
df_merged['ma5_vs_strike'] = (df_merged['ma5'] - df_merged['floor_strike'])/df_merged['floor_strike'] * 100
df_merged['yes_dist_pct'] = df_merged['yes_dist'] / df_merged['floor_strike'] * 100
df_merged['1m_yes_dist_momentum'] = df_merged['yes_dist'] - df_merged['yes_dist'].shift(1)
df_merged['3m_yes_dist_momentum'] = df_merged['yes_dist'] - df_merged['yes_dist'].shift(3)
df_merged['5m_yes_dist_momentum'] = df_merged['yes_dist'] - df_merged['yes_dist'].shift(5)
df_merged['time_decay'] = np.where(df_merged.index.minute % 15 == 0, 0, 15 - df_merged.index.minute % 15)
# df_merged = df_merged.dropna()
df_merged