In [1]:
import sys
import os
import warnings
from datetime import datetime, timezone, timedelta
from pathlib import Path
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns
import pytz
import json
from zoneinfo import ZoneInfo
from pandas import Timestamp
from statsmodels.tsa.stattools import adfuller, kpss, acf, pacf
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.stats.diagnostic import acorr_ljungbox
from statsmodels.tsa.arima.model import ARIMA
from sklearn.model_selection import TimeSeriesSplit
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import r2_score
from scipy.stats import norm

current_dir = Path.cwd()
parent_dir = current_dir.parent
sys.path.insert(0, str(parent_dir))
from lib import *

MODEL_PATH=parent_dir / 'models' 
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 1000)

In [2]:
example_ticker = "KXBTC15M-26MAY040515-15"
lookback_minutes = 10000
series, event_dt = parse_kalshi_15m_event_ticker(example_ticker)
dt_only = get_ticker_datetime(example_ticker)
# crypto_at = datetime(2026,5,5,0,0,tzinfo=ZoneInfo('America/Chicago'))
crypto_at = datetime.now(tz=ZoneInfo('America/Chicago'))
df_api = get_market_data_from_api(series, crypto_at, lookback_minutes)
df_api = df_api.set_index('datetime')
df_api.head()

API Error Response: {'error': {'code': 'not_found', 'message': 'not found', 'service': 'query-exchange'}}
Error getting market candlesticks: 404 Client Error: Not Found for url: https://api.elections.kalshi.com/trade-api/v2/series/KXBTC15M/markets/KXBTC15M-26MAY210215-15/candlesticks?series_ticker=KXBTC15M&ticker=KXBTC15M-26MAY210215-15&start_ts=1779342900&end_ts=1779344100&period_interval=1&include_latest_before_start=True&limit=1000
API Error Response: {'error': {'code': 'not_found', 'message': 'not found', 'service': 'query-exchange'}}
Error getting market candlesticks: 404 Client Error: Not Found for url: https://api.elections.kalshi.com/trade-api/v2/series/KXBTC15M/markets/KXBTC15M-26MAY210230-30/candlesticks?series_ticker=KXBTC15M&ticker=KXBTC15M-26MAY210230-30&start_ts=1779343800&end_ts=1779345000&period_interval=1&include_latest_before_start=True&limit=1000
API Error Response: {'error': {'code': 'not_found', 'message': 'not found', 'service': 'query-exchange'}}
Error getting market candlesticks: 404 Client Error: Not Found for url: https://api.elections.kalshi.com/trade-api/v2/series/KXBTC15M/markets/KXBTC15M-26MAY210245-45/candlesticks?series_ticker=KXBTC15M&ticker=KXBTC15M-26MAY210245-45&start_ts=1779344700&end_ts=1779345900&period_interval=1&include_latest_before_start=True&limit=1000
API Error Response: {'error': {'code': 'not_found', 'message': 'not found', 'service': 'query-exchange'}}
Error getting market candlesticks: 404 Client Error: Not Found for url: https://api.elections.kalshi.com/trade-api/v2/series/KXBTC15M/markets/KXBTC15M-26MAY210300-00/candlesticks?series_ticker=KXBTC15M&ticker=KXBTC15M-26MAY210300-00&start_ts=1779345600&end_ts=1779346800&period_interval=1&include_latest_before_start=True&limit=1000
API Error Response: {'error': {'code': 'not_found', 'message': 'not found', 'service': 'query-exchange'}}
Error getting market candlesticks: 404 Client Error: Not Found for url: https://api.elections.kalshi.com/trade-api/v2/series/KXBTC15M/markets/KXBTC15M-26MAY210315-15/candlesticks?series_ticker=KXBTC15M&ticker=KXBTC15M-26MAY210315-15&start_ts=1779346500&end_ts=1779347700&period_interval=1&include_latest_before_start=True&limit=1000
API Error Response: {'error': {'code': 'not_found', 'message': 'not found', 'service': 'query-exchange'}}
Error getting market candlesticks: 404 Client Error: Not Found for url: https://api.elections.kalshi.com/trade-api/v2/series/KXBTC15M/markets/KXBTC15M-26MAY210330-30/candlesticks?series_ticker=KXBTC15M&ticker=KXBTC15M-26MAY210330-30&start_ts=1779347400&end_ts=1779348600&period_interval=1&include_latest_before_start=True&limit=1000
API Error Response: {'error': {'code': 'not_found', 'message': 'not found', 'service': 'query-exchange'}}
Error getting market candlesticks: 404 Client Error: Not Found for url: https://api.elections.kalshi.com/trade-api/v2/series/KXBTC15M/markets/KXBTC15M-26MAY210345-45/candlesticks?series_ticker=KXBTC15M&ticker=KXBTC15M-26MAY210345-45&start_ts=1779348300&end_ts=1779349500&period_interval=1&include_latest_before_start=True&limit=1000
API Error Response: {'error': {'code': 'not_found', 'message': 'not found', 'service': 'query-exchange'}}
Error getting market candlesticks: 404 Client Error: Not Found for url: https://api.elections.kalshi.com/trade-api/v2/series/KXBTC15M/markets/KXBTC15M-26MAY210400-00/candlesticks?series_ticker=KXBTC15M&ticker=KXBTC15M-26MAY210400-00&start_ts=1779349200&end_ts=1779350400&period_interval=1&include_latest_before_start=True&limit=1000
API Error Response: {'error': {'code': 'not_found', 'message': 'not found', 'service': 'query-exchange'}}
Error getting market candlesticks: 404 Client Error: Not Found for url: https://api.elections.kalshi.com/trade-api/v2/series/KXBTC15M/markets/KXBTC15M-26MAY210415-15/candlesticks?series_ticker=KXBTC15M&ticker=KXBTC15M-26MAY210415-15&start_ts=1779350100&end_ts=1779351300&period_interval=1&include_latest_before_start=True&limit=1000
API Error Response: {'error': {'code': 'not_found', 'message': 'not found', 'service': 'query-exchange'}}
Error getting market candlesticks: 404 Client Error: Not Found for url: https://api.elections.kalshi.com/trade-api/v2/series/KXBTC15M/markets/KXBTC15M-26MAY210430-30/candlesticks?series_ticker=KXBTC15M&ticker=KXBTC15M-26MAY210430-30&start_ts=1779351000&end_ts=1779352200&period_interval=1&include_latest_before_start=True&limit=1000
API Error Response: {'error': {'code': 'not_found', 'message': 'not found', 'service': 'query-exchange'}}
Error getting market candlesticks: 404 Client Error: Not Found for url: https://api.elections.kalshi.com/trade-api/v2/series/KXBTC15M/markets/KXBTC15M-26MAY210445-45/candlesticks?series_ticker=KXBTC15M&ticker=KXBTC15M-26MAY210445-45&start_ts=1779351900&end_ts=1779353100&period_interval=1&include_latest_before_start=True&limit=1000
API Error Response: {'error': {'code': 'not_found', 'message': 'not found', 'service': 'query-exchange'}}
Error getting market candlesticks: 404 Client Error: Not Found for url: https://api.elections.kalshi.com/trade-api/v2/series/KXBTC15M/markets/KXBTC15M-26MAY210500-00/candlesticks?series_ticker=KXBTC15M&ticker=KXBTC15M-26MAY210500-00&start_ts=1779352800&end_ts=1779354000&period_interval=1&include_latest_before_start=True&limit=1000

,ticker,floor_strike,volume_fp,open_interest_fp,yes_ask_open_dollar,yes_ask_high_dollar,yes_ask_low_dollar,yes_ask_close_dollar,yes_bid_open_dollar,yes_bid_high_dollar,yes_bid_low_dollar,yes_bid_close_dollar,no_ask_open_dollar,no_ask_high_dollar,no_ask_low_dollar,no_ask_close_dollar,no_bid_open_dollar,no_bid_high_dollar,no_bid_low_dollar,no_bid_close_dollar
datetime,,,,,,,,,,,,,,,,,,,,
2026-05-16 13:46:00-05:00,KXBTC15M-26MAY161500-00,78236.47,19917.54,17044.97,0.999,0.999,0.38,0.38,0.00,0.48,0.00,0.37,0.63,0.52,1.00,1.00,0.62,0.001,0.62,0.001
2026-05-16 13:47:00-05:00,KXBTC15M-26MAY161500-00,78236.47,23708.44,36504.48,0.380,0.420,0.38,0.41,0.37,0.40,0.37,0.40,0.60,0.60,0.63,0.63,0.59,0.580,0.62,0.620
2026-05-16 13:48:00-05:00,KXBTC15M-26MAY161500-00,78236.47,17160.48,49749.90,0.410,0.460,0.41,0.44,0.40,0.44,0.40,0.43,0.57,0.56,0.60,0.60,0.56,0.540,0.59,0.590
2026-05-16 13:49:00-05:00,KXBTC15M-26MAY161500-00,78236.47,22812.78,49237.02,0.440,0.590,0.43,0.57,0.43,0.58,0.41,0.56,0.44,0.42,0.59,0.57,0.43,0.410,0.57,0.560
2026-05-16 13:50:00-05:00,KXBTC15M-26MAY161500-00,78236.47,23922.68,52366.07,0.570,0.620,0.32,0.32,0.56,0.60,0.31,0.31,0.69,0.40,0.69,0.44,0.68,0.380,0.68,0.430

In [3]:
df_crypto = get_crypto_past_minutes(series, crypto_at, lookback_minutes)
df_crypto['datetime'] = pd.to_datetime(df_crypto['datetime'])
df_crypto['datetime'] = df_crypto['datetime'].dt.tz_convert('America/Chicago')
df_crypto['datetime'] = df_crypto['datetime'].dt.floor('min')
df_crypto = df_crypto.set_index('datetime')
filter_timestamp = df_crypto[df_crypto.index.minute.isin([0,15,30,45])].index[0]
df_crypto = df_crypto[df_crypto.index >= filter_timestamp]
df_crypto.head()

                               open      high       low     close  tick_count
datetime
2026-05-11 11:45:00-05:00  81623.60  81623.88  81548.21  81569.80          41
2026-05-11 11:46:00-05:00  81565.10  81654.75  81559.09  81627.50          52
2026-05-11 11:47:00-05:00  81621.83  81632.41  81617.68  81618.15          12
2026-05-11 11:48:00-05:00  81622.48  81622.48  81622.48  81622.48           0
2026-05-11 11:49:00-05:00  81683.92  81683.92  81683.92  81683.92           0

In [4]:
df_merged = df_crypto.join(df_api, how='left')
df_merged = df_merged.dropna()
df_merged.head()

,open,high,low,close,tick_count,ticker,floor_strike,volume_fp,open_interest_fp,yes_ask_open_dollar,yes_ask_high_dollar,yes_ask_low_dollar,yes_ask_close_dollar,yes_bid_open_dollar,yes_bid_high_dollar,yes_bid_low_dollar,yes_bid_close_dollar,no_ask_open_dollar,no_ask_high_dollar,no_ask_low_dollar,no_ask_close_dollar,no_bid_open_dollar,no_bid_high_dollar,no_bid_low_dollar,no_bid_close_dollar
datetime,,,,,,,,,,,,,,,,,,,,,,,,,
2026-05-16 13:46:00-05:00,78229.56,78229.56,78229.14,78229.14,0,KXBTC15M-26MAY161500-00,78236.47,19917.54,17044.97,0.999,0.999,0.38,0.38,0.00,0.48,0.00,0.37,0.63,0.52,1.00,1.00,0.62,0.001,0.62,0.001
2026-05-16 13:47:00-05:00,78220.09,78220.09,78220.09,78220.09,0,KXBTC15M-26MAY161500-00,78236.47,23708.44,36504.48,0.380,0.420,0.38,0.41,0.37,0.40,0.37,0.40,0.60,0.60,0.63,0.63,0.59,0.580,0.62,0.620
2026-05-16 13:48:00-05:00,78222.18,78227.90,78222.18,78226.89,12,KXBTC15M-26MAY161500-00,78236.47,17160.48,49749.90,0.410,0.460,0.41,0.44,0.40,0.44,0.40,0.43,0.57,0.56,0.60,0.60,0.56,0.540,0.59,0.590
2026-05-16 13:49:00-05:00,78227.48,78227.48,78227.30,78227.30,1,KXBTC15M-26MAY161500-00,78236.47,22812.78,49237.02,0.440,0.590,0.43,0.57,0.43,0.58,0.41,0.56,0.44,0.42,0.59,0.57,0.43,0.410,0.57,0.560
2026-05-16 13:50:00-05:00,78246.53,78249.21,78234.33,78234.84,19,KXBTC15M-26MAY161500-00,78236.47,23922.68,52366.07,0.570,0.620,0.32,0.32,0.56,0.60,0.31,0.31,0.69,0.40,0.69,0.44,0.68,0.380,0.68,0.430

In [5]:
df_calc = df_merged

In [6]:
def rsi_calc(series, periods=14):
    delta = series.diff()
    gain = (delta.where(delta>0,0)).rolling(periods).mean()
    loss = (delta.where(delta<0,0)).rolling(periods).mean()
    rs = gain / loss
    rsi = 100 - (100/(1+rs))
    return rsi

In [7]:
def macd_calc(series, fast=14, slow=26, signal=13):
    ema_fast = series.ewm(span=fast, adjust=False).mean()
    ema_slow = series.ewm(span=slow, adjust=False).mean()
    macd_line = ema_fast - ema_slow
    signal_line = macd_line.ewm(span=signal, adjust=False).mean()
    histogram = macd_line - signal_line
    return macd_line, signal_line, histogram

In [8]:
research_side = 'yes'
df_calc['rsi'] = rsi_calc(df_calc['close'], periods=5) 
df_calc['macd'], df_calc['signal_line'], _ = macd_calc(df_calc['close'], 4, 9, 2) 
df_calc[research_side + '_dist'] = df_calc['close'] - df_calc['floor_strike']
df_calc['log_return'] = np.log(df_calc['close'] / df_calc['close'].shift(1))
df_calc['m3_log_return'] = df_calc['log_return'].rolling(3).std()
df_calc['m5_log_return'] = df_calc['log_return'].rolling(5).std()
df_calc['ma3'] = df_calc['close'].rolling(3).mean()
df_calc['ma5'] = df_calc['close'].rolling(5).mean()
df_calc['ma3_vs_strike'] = (df_calc['ma3'] - df_calc['floor_strike'])/df_calc['floor_strike'] * 100
df_calc['ma5_vs_strike'] = (df_calc['ma5'] - df_calc['floor_strike'])/df_calc['floor_strike'] * 100
df_calc[research_side + '_dist_pct'] = df_calc[research_side + '_dist'] / df_calc['floor_strike'] * 100
df_calc['m1_' + research_side + '_dist_momentum'] = df_calc[research_side + '_dist'] - df_calc[research_side + '_dist'].shift(1)
df_calc['m3_' + research_side + '_dist_momentum'] = df_calc[research_side + '_dist'] - df_calc[research_side + '_dist'].shift(3)
df_calc['m5_' + research_side + '_dist_momentum'] = df_calc[research_side + '_dist'] - df_calc[research_side + '_dist'].shift(5)
df_calc['time_decay'] = np.where(df_calc.index.minute % 15 == 0, 0, 15 - df_calc.index.minute % 15)
df_calc['hour'] = df_calc.index.hour
df_calc['minute'] = df_calc.index.minute
df_calc[research_side + '_spread'] = df_calc[research_side + '_ask_close_dollar'] - df_calc[research_side + '_bid_close_dollar']
df_calc['volume_surge'] = df_calc['volume_fp'] / df_calc['volume_fp'].rolling(5).mean()
df_calc['ask_delta'] = df_calc[research_side + '_ask_low_dollar'].diff()
df_calc['bid_delta'] = df_calc[research_side + '_bid_high_dollar'].diff()
df_calc['ask_std'] = df_calc[research_side + '_ask_low_dollar'].rolling(3).std()
df_calc['bid_std'] = df_calc[research_side + '_bid_high_dollar'].rolling(3).std()
# df_calc['oi_change'] = df_calc['open_interest_fp'] - df_calc['open_interest_fp'].shift(1)

In [9]:
df_calc = df_calc.dropna()

In [10]:
df_calc.head()

,open,high,low,close,tick_count,ticker,floor_strike,volume_fp,open_interest_fp,yes_ask_open_dollar,yes_ask_high_dollar,yes_ask_low_dollar,yes_ask_close_dollar,yes_bid_open_dollar,yes_bid_high_dollar,yes_bid_low_dollar,yes_bid_close_dollar,no_ask_open_dollar,no_ask_high_dollar,no_ask_low_dollar,no_ask_close_dollar,no_bid_open_dollar,no_bid_high_dollar,no_bid_low_dollar,no_bid_close_dollar,rsi,macd,signal_line,yes_dist,log_return,m3_log_return,m5_log_return,ma3,ma5,ma3_vs_strike,ma5_vs_strike,yes_dist_pct,m1_yes_dist_momentum,m3_yes_dist_momentum,m5_yes_dist_momentum,time_decay,hour,minute,yes_spread,volume_surge,ask_delta,bid_delta,ask_std,bid_std
datetime,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-05-16 13:51:00-05:00,78210.49,78242.44,78210.21,78241.03,55,KXBTC15M-26MAY161500-00,78236.47,25382.20,59247.27,0.32,0.540,0.32,0.54,0.31,0.530,0.31,0.53,0.47,0.470,0.69,0.69,0.46,0.460,0.68,0.68,176.114382,3.112784,2.224786,4.56,0.000079,0.000048,0.000089,78234.390000,78230.030,-0.002659,-0.008231,0.005828,6.19,14.14,11.89,9,13,51,0.01,1.123240,0.00,-0.070,0.063509,0.036056
2026-05-16 13:52:00-05:00,78238.47,78255.38,78235.16,78254.43,60,KXBTC15M-26MAY161500-00,78236.47,25990.18,60521.71,0.54,0.650,0.46,0.65,0.53,0.640,0.45,0.64,0.36,0.360,0.55,0.47,0.35,0.350,0.54,0.46,100.000000,6.509130,5.081015,17.96,0.000171,0.000049,0.000059,78243.433333,78236.898,0.008900,0.000547,0.022956,13.40,27.13,34.34,8,13,52,0.01,1.127377,0.14,0.110,0.080829,0.055678
2026-05-16 13:53:00-05:00,78250.35,78250.35,78249.52,78249.52,0,KXBTC15M-26MAY161500-00,78236.47,45794.19,66959.97,0.65,0.920,0.65,0.86,0.64,0.919,0.64,0.85,0.15,0.081,0.36,0.36,0.14,0.080,0.35,0.35,121.696863,6.636645,6.118102,13.05,-0.000063,0.000118,0.000090,78248.326667,78241.424,0.015155,0.006332,0.016680,-4.91,14.68,22.63,7,13,53,0.01,1.591159,0.19,0.279,0.165630,0.200525
2026-05-16 13:54:00-05:00,78281.56,78307.83,78280.59,78287.22,22,KXBTC15M-26MAY161500-00,78236.47,51480.36,72507.14,0.86,0.947,0.73,0.81,0.85,0.941,0.72,0.80,0.20,0.059,0.28,0.15,0.19,0.053,0.27,0.14,108.194259,13.706921,11.177315,50.75,0.000482,0.000273,0.000202,78263.723333,78253.408,0.034835,0.021650,0.064867,37.70,46.19,59.92,6,13,54,0.01,1.491582,0.08,0.022,0.138684,0.167793
2026-05-16 13:55:00-05:00,78272.71,78274.83,78270.35,78270.35,4,KXBTC15M-26MAY161500-00,78236.47,46691.54,87338.23,0.81,0.860,0.21,0.22,0.80,0.840,0.20,0.21,0.79,0.160,0.80,0.20,0.78,0.140,0.79,0.19,161.334835,12.630100,12.145838,33.88,-0.000216,0.000366,0.000263,78269.030000,78260.510,0.041617,0.030727,0.043305,-16.87,15.92,35.51,5,13,55,0.01,1.195145,-0.52,-0.101,0.280000,0.053113

In [17]:
def agg_data_function(df, column, *data_cents):
    results = {cent: [] for cent in data_cents}
    triggered = set() 
    
    for i in range(len(df)):
        row = df.iloc[i]
        
        if row['time_decay'] == 0:
            continue
        
        current_ticker = row['ticker']
        
        for cent in data_cents:
            if (current_ticker, cent) in triggered:
                continue
                
            if float(row[column + '_ask_low_dollar']) < float(cent):
                # print(f"trigger: {column + '_ask_low_dollar'}: {row[column + '_ask_low_dollar']}")
                triggered.add((current_ticker, cent)) 
                
                high_price = 0
                low_price = 1
                
                for j in range(1, 16):
                    if i + j >= len(df):
                        break
                    next_row = df.iloc[i + j]
                    high_price = max(next_row[column + '_bid_high_dollar'], high_price)
                    low_price = min(next_row[column + '_ask_low_dollar'], low_price)
                    if next_row['ticker'] != current_ticker or next_row['time_decay'] == 0:
                        break
                
                tmp_dict = row.to_dict()
                tmp_dict['subsequent_high'] = high_price
                tmp_dict['subsequent_low'] = low_price
                tmp_dict['reached_30'] = 1 if high_price >= 0.30 else 0
                tmp_dict['reached_40'] = 1 if high_price >= 0.40 else 0
                tmp_dict['reached_50'] = 1 if high_price >= 0.50 else 0
                tmp_dict['reached_60'] = 1 if high_price >= 0.60 else 0
                tmp_dict['reached_70'] = 1 if high_price >= 0.7 else 0
                tmp_dict['reached_90'] = 1 if high_price >= 0.9 else 0
                tmp_dict['reached_99'] = 1 if high_price >= 0.99 else 0
                results[cent].append(tmp_dict)
                
    
    return results

In [18]:
res=agg_data_function(df_calc, research_side, *[0.05,0.1,0.15,0.2,0.25,0.3,0.35])

In [19]:
# win rate analysis
comb_05 = pd.DataFrame(res[0.05])
comb_10 = pd.DataFrame(res[0.10])
comb_15 = pd.DataFrame(res[0.15])
comb_20 = pd.DataFrame(res[0.2])
comb_25 = pd.DataFrame(res[0.25])
comb_30 = pd.DataFrame(res[0.3])
comb_35 = pd.DataFrame(res[0.35])

In [20]:
def get_protential_pnl(df, entry_price, *exit_price):
    for price in exit_price:
        col_name = f"reached_{int(price * 100)}"
        if col_name in df.columns:
            rate = (df[col_name] == 1).sum() / len(df)
            pnl = rate * (float(price) - float(entry_price))
            print(f"Entry: {entry_price}, Exit: {price}, win rate: {rate:.2%}, PNL: {pnl:.4f}")

In [21]:
def evaluate_feature(good_mean, good_std, bad_mean, bad_std):
    diff = good_mean - bad_mean
    avg_std = (good_std + bad_std) / 2
    
    if avg_std < 1e-10:
        return None
    
    ratio = abs(diff) / avg_std
    
    if ratio > 0.5:
        grade = 'strong'
    elif ratio > 0.3:
        grade = 'medium'
    elif ratio > 0.15:
        grade = 'weak'
    else:
        grade = 'useless'
    
    return ratio, grade

In [38]:
good_hours = [9,10,11,12,13,14,15,16,20]

get_protential_pnl(comb_05[comb_05['hour'].isin(good_hours)],0.05,*[0.4,0.5,0.6,0.7,0.9,0.99])
get_protential_pnl(comb_10[comb_10['hour'].isin(good_hours)],0.10,*[0.4,0.5,0.6,0.7,0.9,0.99])
get_protential_pnl(comb_15[comb_15['hour'].isin(good_hours)],0.15,*[0.4,0.5,0.6,0.7,0.9,0.99])
get_protential_pnl(comb_20[comb_20['hour'].isin(good_hours)],0.20,*[0.4,0.5,0.6,0.7,0.9,0.99])
get_protential_pnl(comb_25[comb_25['hour'].isin(good_hours)],0.25,*[0.4,0.5,0.6,0.7,0.9,0.99])
get_protential_pnl(comb_30[comb_30['hour'].isin(good_hours)],0.30,*[0.4,0.5,0.6,0.7,0.9,0.99])
get_protential_pnl(comb_35[comb_35['hour'].isin(good_hours)],0.35,*[0.4,0.5,0.6,0.7,0.9,0.99])

Entry: 0.05, Exit: 0.4, win rate: 14.04%, PNL: 0.0491
Entry: 0.05, Exit: 0.5, win rate: 12.28%, PNL: 0.0553
Entry: 0.05, Exit: 0.6, win rate: 10.53%, PNL: 0.0579
Entry: 0.05, Exit: 0.7, win rate: 10.53%, PNL: 0.0684
Entry: 0.05, Exit: 0.9, win rate: 8.77%, PNL: 0.0746
Entry: 0.05, Exit: 0.99, win rate: 8.77%, PNL: 0.0825
Entry: 0.1, Exit: 0.4, win rate: 24.24%, PNL: 0.0727
Entry: 0.1, Exit: 0.5, win rate: 22.73%, PNL: 0.0909
Entry: 0.1, Exit: 0.6, win rate: 21.21%, PNL: 0.1061
Entry: 0.1, Exit: 0.7, win rate: 19.70%, PNL: 0.1182
Entry: 0.1, Exit: 0.9, win rate: 18.18%, PNL: 0.1455
Entry: 0.1, Exit: 0.99, win rate: 16.67%, PNL: 0.1483
Entry: 0.15, Exit: 0.4, win rate: 34.29%, PNL: 0.0857
Entry: 0.15, Exit: 0.5, win rate: 30.00%, PNL: 0.1050
Entry: 0.15, Exit: 0.6, win rate: 28.57%, PNL: 0.1286
Entry: 0.15, Exit: 0.7, win rate: 24.29%, PNL: 0.1336
Entry: 0.15, Exit: 0.9, win rate: 21.43%, PNL: 0.1607
Entry: 0.15, Exit: 0.99, win rate: 20.00%, PNL: 0.1680
Entry: 0.2, Exit: 0.4, win rate: 44.00%, PNL: 0.0880
Entry: 0.2, Exit: 0.5, win rate: 34.67%, PNL: 0.1040
Entry: 0.2, Exit: 0.6, win rate: 32.00%, PNL: 0.1280
Entry: 0.2, Exit: 0.7, win rate: 28.00%, PNL: 0.1400
Entry: 0.2, Exit: 0.9, win rate: 25.33%, PNL: 0.1773
Entry: 0.2, Exit: 0.99, win rate: 24.00%, PNL: 0.1896
Entry: 0.25, Exit: 0.4, win rate: 56.79%, PNL: 0.0852
Entry: 0.25, Exit: 0.5, win rate: 45.68%, PNL: 0.1142
Entry: 0.25, Exit: 0.6, win rate: 40.74%, PNL: 0.1426
Entry: 0.25, Exit: 0.7, win rate: 34.57%, PNL: 0.1556
Entry: 0.25, Exit: 0.9, win rate: 29.63%, PNL: 0.1926
Entry: 0.25, Exit: 0.99, win rate: 28.40%, PNL: 0.2101
Entry: 0.3, Exit: 0.4, win rate: 68.89%, PNL: 0.0689
Entry: 0.3, Exit: 0.5, win rate: 58.89%, PNL: 0.1178
Entry: 0.3, Exit: 0.6, win rate: 52.22%, PNL: 0.1567
Entry: 0.3, Exit: 0.7, win rate: 43.33%, PNL: 0.1733
Entry: 0.3, Exit: 0.9, win rate: 35.56%, PNL: 0.2133
Entry: 0.3, Exit: 0.99, win rate: 34.44%, PNL: 0.2377
Entry: 0.35, Exit: 0.4, win rate: 76.77%, PNL: 0.0384
Entry: 0.35, Exit: 0.5, win rate: 66.67%, PNL: 0.1000
Entry: 0.35, Exit: 0.6, win rate: 60.61%, PNL: 0.1515
Entry: 0.35, Exit: 0.7, win rate: 49.49%, PNL: 0.1732
Entry: 0.35, Exit: 0.9, win rate: 42.42%, PNL: 0.2333
Entry: 0.35, Exit: 0.99, win rate: 39.39%, PNL: 0.2521

In [39]:
feature_cols = [  
    'ask_delta',
    'bid_delta',
    'ask_std',
    'bid_std',
    research_side + '_dist',         
    'log_return',  
    'm3_log_return',
    'm5_log_return',  
    'ma3_vs_strike',
    'ma5_vs_strike',            
    research_side + '_dist_pct',
    'm1_' + research_side + '_dist_momentum',
    'm3_' + research_side + '_dist_momentum',
    'm5_' + research_side + '_dist_momentum',
    'time_decay',
    'hour',
    'minute',
    research_side + '_spread',
    'volume_surge',
    'rsi',
    'macd',
    'signal_line',
]

comb_list = [0.05, 0.1, 0.15, 0.2, 0.25,0.3,0.35]
reached_list = ['reached_30','reached_40', 'reached_50', 'reached_60', 'reached_70', 'reached_90', 'reached_99']

for comb in comb_list: 
    for reached in reached_list:
        df_results = pd.DataFrame(res[comb])
        df_results = df_results[df_results['hour'].isin(good_hours)]
        df_expected = df_results[reached]
        
        # Separate good and bad outcomes
        good = df_results[df_expected == 1]
        bad = df_results[df_expected == 0]
        
        # Prior probabilities
        prior_good = len(good) / len(df_results)
        prior_bad = len(bad) / len(df_results)
        print(f"Comb is {comb}, reached is {reached}")
        print(f"Prior P(Good) = {prior_good:.4f}, P(Bad) = {prior_bad:.4f}")
        likelihoods = {}
        good_ratio_count = 0
        for col in feature_cols:
            good_mean, good_std = good[col].mean(), good[col].std()
            bad_mean, bad_std = bad[col].mean(), bad[col].std()
            
            likelihoods[col] = {
                'good': (good_mean, good_std),
                'bad': (bad_mean, bad_std),
            }
            
            diff = good_mean - bad_mean
            ratio, grade = evaluate_feature(good_mean, good_std, bad_mean, bad_std)
            if grade == 'strong' or grade == 'medium':
                good_ratio_count += 1
            print(f"{grade} -> {col}: Good={good_mean:.4f}, Bad={bad_mean:.4f}, ratio={ratio:.4f}")
        print(f"Total Good Ratio is {good_ratio_count}\n")

Comb is 0.05, reached is reached_30
Prior P(Good) = 0.1404, P(Bad) = 0.8596
medium -> ask_delta: Good=-0.0803, Bad=-0.1191, ratio=0.4979
medium -> bid_delta: Good=-0.0734, Bad=-0.1190, ratio=0.4242
weak -> ask_std: Good=0.0803, Bad=0.0968, ratio=0.2426
weak -> bid_std: Good=0.0834, Bad=0.0988, ratio=0.1676
useless -> yes_dist: Good=-79.7575, Bad=-87.2198, ratio=0.1215
useless -> log_return: Good=-0.0003, Bad=-0.0003, ratio=0.0127
medium -> m3_log_return: Good=0.0003, Bad=0.0004, ratio=0.4022
useless -> m5_log_return: Good=0.0005, Bad=0.0005, ratio=0.0034
weak -> ma3_vs_strike: Good=-0.0781, Bad=-0.0967, ratio=0.2594
weak -> ma5_vs_strike: Good=-0.0692, Bad=-0.0862, ratio=0.2345
useless -> yes_dist_pct: Good=-0.1038, Bad=-0.1134, ratio=0.1210
useless -> m1_yes_dist_momentum: Good=-20.3338, Bad=-20.8720, ratio=0.0128
useless -> m3_yes_dist_momentum: Good=-41.2500, Bad=-32.0820, ratio=0.1420
useless -> m5_yes_dist_momentum: Good=-56.6462, Bad=-49.5865, ratio=0.0866
medium -> time_decay: Good=4.8750, Bad=3.6939, ratio=0.4978
weak -> hour: Good=12.5000, Bad=11.7755, ratio=0.2395
strong -> minute: Good=28.8750, Bad=36.4082, ratio=0.5589
weak -> yes_spread: Good=0.0040, Bad=0.0047, ratio=0.2579
strong -> volume_surge: Good=0.9854, Bad=1.3530, ratio=1.0645
weak -> rsi: Good=-358.7965, Bad=-948.9691, ratio=0.1738
medium -> macd: Good=-22.6398, Bad=-15.3425, ratio=0.4010
medium -> signal_line: Good=-21.3065, Bad=-14.2689, ratio=0.4205
Total Good Ratio is 8

Comb is 0.05, reached is reached_40
Prior P(Good) = 0.1404, P(Bad) = 0.8596
medium -> ask_delta: Good=-0.0803, Bad=-0.1191, ratio=0.4979
medium -> bid_delta: Good=-0.0734, Bad=-0.1190, ratio=0.4242
weak -> ask_std: Good=0.0803, Bad=0.0968, ratio=0.2426
weak -> bid_std: Good=0.0834, Bad=0.0988, ratio=0.1676
useless -> yes_dist: Good=-79.7575, Bad=-87.2198, ratio=0.1215
useless -> log_return: Good=-0.0003, Bad=-0.0003, ratio=0.0127
medium -> m3_log_return: Good=0.0003, Bad=0.0004, ratio=0.4022
useless -> m5_log_return: Good=0.0005, Bad=0.0005, ratio=0.0034
weak -> ma3_vs_strike: Good=-0.0781, Bad=-0.0967, ratio=0.2594
weak -> ma5_vs_strike: Good=-0.0692, Bad=-0.0862, ratio=0.2345
useless -> yes_dist_pct: Good=-0.1038, Bad=-0.1134, ratio=0.1210
useless -> m1_yes_dist_momentum: Good=-20.3338, Bad=-20.8720, ratio=0.0128
useless -> m3_yes_dist_momentum: Good=-41.2500, Bad=-32.0820, ratio=0.1420
useless -> m5_yes_dist_momentum: Good=-56.6462, Bad=-49.5865, ratio=0.0866
medium -> time_decay: Good=4.8750, Bad=3.6939, ratio=0.4978
weak -> hour: Good=12.5000, Bad=11.7755, ratio=0.2395
strong -> minute: Good=28.8750, Bad=36.4082, ratio=0.5589
weak -> yes_spread: Good=0.0040, Bad=0.0047, ratio=0.2579
strong -> volume_surge: Good=0.9854, Bad=1.3530, ratio=1.0645
weak -> rsi: Good=-358.7965, Bad=-948.9691, ratio=0.1738
medium -> macd: Good=-22.6398, Bad=-15.3425, ratio=0.4010
medium -> signal_line: Good=-21.3065, Bad=-14.2689, ratio=0.4205
Total Good Ratio is 8

Comb is 0.05, reached is reached_50
Prior P(Good) = 0.1228, P(Bad) = 0.8772
medium -> ask_delta: Good=-0.0816, Bad=-0.1181, ratio=0.4624
medium -> bid_delta: Good=-0.0796, Bad=-0.1172, ratio=0.3442
useless -> ask_std: Good=0.0855, Bad=0.0957, ratio=0.1493
useless -> bid_std: Good=0.0903, Bad=0.0975, ratio=0.0758
useless -> yes_dist: Good=-78.3886, Bad=-87.2622, ratio=0.1413
useless -> log_return: Good=-0.0003, Bad=-0.0003, ratio=0.0818
medium -> m3_log_return: Good=0.0003, Bad=0.0004, ratio=0.4265
useless -> m5_log_return: Good=0.0005, Bad=0.0005, ratio=0.0118
medium -> ma3_vs_strike: Good=-0.0748, Bad=-0.0968, ratio=0.3008
weak -> ma5_vs_strike: Good=-0.0679, Bad=-0.0861, ratio=0.2444
useless -> yes_dist_pct: Good=-0.1017, Bad=-0.1135, ratio=0.1452
useless -> m1_yes_dist_momentum: Good=-23.8729, Bad=-20.3658, ratio=0.0815
useless -> m3_yes_dist_momentum: Good=-39.1286, Bad=-32.5624, ratio=0.0980
weak -> m5_yes_dist_momentum: Good=-63.3429, Bad=-48.7902, ratio=0.1753
medium -> time_decay: Good=4.5714, Bad=3.7600, ratio=0.3387
medium -> hour: Good=12.8571, Bad=11.7400, ratio=0.3612
strong -> minute: Good=27.5714, Bad=36.4400, ratio=0.6603
medium -> yes_spread: Good=0.0037, Bad=0.0048, ratio=0.3647
strong -> volume_surge: Good=1.0016, Bad=1.3434, ratio=0.9536
weak -> rsi: Good=-335.7002, Bad=-940.3992, ratio=0.1778
medium -> macd: Good=-21.4426, Bad=-15.6561, ratio=0.3118
medium -> signal_line: Good=-19.9741, Bad=-14.5962, ratio=0.3176
Total Good Ratio is 11

Comb is 0.05, reached is reached_60
Prior P(Good) = 0.1053, P(Bad) = 0.8947
strong -> ask_delta: Good=-0.0755, Bad=-0.1181, ratio=0.5402
weak -> bid_delta: Good=-0.0895, Bad=-0.1153, ratio=0.2328
useless -> ask_std: Good=0.0884, Bad=0.0952, ratio=0.0964
useless -> bid_std: Good=0.0937, Bad=0.0970, ratio=0.0327
weak -> yes_dist: Good=-77.2200, Bad=-87.2257, ratio=0.1544
useless -> log_return: Good=-0.0003, Bad=-0.0003, ratio=0.1415
weak -> m3_log_return: Good=0.0003, Bad=0.0004, ratio=0.2950
useless -> m5_log_return: Good=0.0005, Bad=0.0005, ratio=0.0236
medium -> ma3_vs_strike: Good=-0.0704, Bad=-0.0969, ratio=0.3541
weak -> ma5_vs_strike: Good=-0.0654, Bad=-0.0860, ratio=0.2692
weak -> yes_dist_pct: Good=-0.1002, Bad=-0.1135, ratio=0.1581
useless -> m1_yes_dist_momentum: Good=-26.4600, Bad=-20.1302, ratio=0.1411
useless -> m3_yes_dist_momentum: Good=-41.6650, Bad=-32.3927, ratio=0.1322
useless -> m5_yes_dist_momentum: Good=-46.7083, Bad=-51.0325, ratio=0.0540
medium -> time_decay: Good=4.6667, Bad=3.7647, ratio=0.3617
medium -> hour: Good=13.1667, Bad=11.7255, ratio=0.4479
strong -> minute: Good=25.3333, Bad=36.5294, ratio=0.8733
medium -> yes_spread: Good=0.0037, Bad=0.0047, ratio=0.3623
strong -> volume_surge: Good=1.0031, Bad=1.3365, ratio=0.8883
weak -> rsi: Good=-391.6502, Bad=-921.9600, ratio=0.1554
weak -> macd: Good=-20.0435, Bad=-15.9341, ratio=0.2159
weak -> signal_line: Good=-18.5491, Bad=-14.8693, ratio=0.2134
Total Good Ratio is 7

Comb is 0.05, reached is reached_70
Prior P(Good) = 0.1053, P(Bad) = 0.8947
strong -> ask_delta: Good=-0.0755, Bad=-0.1181, ratio=0.5402
weak -> bid_delta: Good=-0.0895, Bad=-0.1153, ratio=0.2328
useless -> ask_std: Good=0.0884, Bad=0.0952, ratio=0.0964
useless -> bid_std: Good=0.0937, Bad=0.0970, ratio=0.0327
weak -> yes_dist: Good=-77.2200, Bad=-87.2257, ratio=0.1544
useless -> log_return: Good=-0.0003, Bad=-0.0003, ratio=0.1415
weak -> m3_log_return: Good=0.0003, Bad=0.0004, ratio=0.2950
useless -> m5_log_return: Good=0.0005, Bad=0.0005, ratio=0.0236
medium -> ma3_vs_strike: Good=-0.0704, Bad=-0.0969, ratio=0.3541
weak -> ma5_vs_strike: Good=-0.0654, Bad=-0.0860, ratio=0.2692
weak -> yes_dist_pct: Good=-0.1002, Bad=-0.1135, ratio=0.1581
useless -> m1_yes_dist_momentum: Good=-26.4600, Bad=-20.1302, ratio=0.1411
useless -> m3_yes_dist_momentum: Good=-41.6650, Bad=-32.3927, ratio=0.1322
useless -> m5_yes_dist_momentum: Good=-46.7083, Bad=-51.0325, ratio=0.0540
medium -> time_decay: Good=4.6667, Bad=3.7647, ratio=0.3617
medium -> hour: Good=13.1667, Bad=11.7255, ratio=0.4479
strong -> minute: Good=25.3333, Bad=36.5294, ratio=0.8733
medium -> yes_spread: Good=0.0037, Bad=0.0047, ratio=0.3623
strong -> volume_surge: Good=1.0031, Bad=1.3365, ratio=0.8883
weak -> rsi: Good=-391.6502, Bad=-921.9600, ratio=0.1554
weak -> macd: Good=-20.0435, Bad=-15.9341, ratio=0.2159
weak -> signal_line: Good=-18.5491, Bad=-14.8693, ratio=0.2134
Total Good Ratio is 7

Comb is 0.05, reached is reached_90
Prior P(Good) = 0.0877, P(Bad) = 0.9123
medium -> ask_delta: Good=-0.0792, Bad=-0.1170, ratio=0.4682
useless -> bid_delta: Good=-0.1020, Bad=-0.1136, ratio=0.1030
useless -> ask_std: Good=0.1001, Bad=0.0940, ratio=0.0882
useless -> bid_std: Good=0.1095, Bad=0.0954, ratio=0.1356
useless -> yes_dist: Good=-86.8200, Bad=-86.1102, ratio=0.0109
medium -> log_return: Good=-0.0004, Bad=-0.0003, ratio=0.3252
weak -> m3_log_return: Good=0.0003, Bad=0.0004, ratio=0.1635
weak -> m5_log_return: Good=0.0005, Bad=0.0005, ratio=0.2372
weak -> ma3_vs_strike: Good=-0.0748, Bad=-0.0960, ratio=0.2723
weak -> ma5_vs_strike: Good=-0.0674, Bad=-0.0854, ratio=0.2248
useless -> yes_dist_pct: Good=-0.1126, Bad=-0.1120, ratio=0.0070
medium -> m1_yes_dist_momentum: Good=-34.3700, Bad=-19.4913, ratio=0.3251
medium -> m3_yes_dist_momentum: Good=-54.0540, Bad=-31.3798, ratio=0.3160
useless -> m5_yes_dist_momentum: Good=-59.9500, Bad=-49.6762, ratio=0.1281
strong -> time_decay: Good=5.2000, Bad=3.7308, ratio=0.5988
weak -> hour: Good=12.6000, Bad=11.8077, ratio=0.2364
strong -> minute: Good=27.8000, Bad=36.0769, ratio=0.6793
weak -> yes_spread: Good=0.0040, Bad=0.0047, ratio=0.2250
strong -> volume_surge: Good=0.9313, Bad=1.3370, ratio=1.0865
useless -> rsi: Good=-493.9803, Bad=-901.9223, ratio=0.1189
medium -> macd: Good=-23.4397, Bad=-15.6866, ratio=0.4128
medium -> signal_line: Good=-21.3114, Bad=-14.6745, ratio=0.3887
Total Good Ratio is 9

Comb is 0.05, reached is reached_99
Prior P(Good) = 0.0877, P(Bad) = 0.9123
medium -> ask_delta: Good=-0.0792, Bad=-0.1170, ratio=0.4682
useless -> bid_delta: Good=-0.1020, Bad=-0.1136, ratio=0.1030
useless -> ask_std: Good=0.1001, Bad=0.0940, ratio=0.0882
useless -> bid_std: Good=0.1095, Bad=0.0954, ratio=0.1356
useless -> yes_dist: Good=-86.8200, Bad=-86.1102, ratio=0.0109
medium -> log_return: Good=-0.0004, Bad=-0.0003, ratio=0.3252
weak -> m3_log_return: Good=0.0003, Bad=0.0004, ratio=0.1635
weak -> m5_log_return: Good=0.0005, Bad=0.0005, ratio=0.2372
weak -> ma3_vs_strike: Good=-0.0748, Bad=-0.0960, ratio=0.2723
weak -> ma5_vs_strike: Good=-0.0674, Bad=-0.0854, ratio=0.2248
useless -> yes_dist_pct: Good=-0.1126, Bad=-0.1120, ratio=0.0070
medium -> m1_yes_dist_momentum: Good=-34.3700, Bad=-19.4913, ratio=0.3251
medium -> m3_yes_dist_momentum: Good=-54.0540, Bad=-31.3798, ratio=0.3160
useless -> m5_yes_dist_momentum: Good=-59.9500, Bad=-49.6762, ratio=0.1281
strong -> time_decay: Good=5.2000, Bad=3.7308, ratio=0.5988
weak -> hour: Good=12.6000, Bad=11.8077, ratio=0.2364
strong -> minute: Good=27.8000, Bad=36.0769, ratio=0.6793
weak -> yes_spread: Good=0.0040, Bad=0.0047, ratio=0.2250
strong -> volume_surge: Good=0.9313, Bad=1.3370, ratio=1.0865
useless -> rsi: Good=-493.9803, Bad=-901.9223, ratio=0.1189
medium -> macd: Good=-23.4397, Bad=-15.6866, ratio=0.4128
medium -> signal_line: Good=-21.3114, Bad=-14.6745, ratio=0.3887
Total Good Ratio is 9

Comb is 0.1, reached is reached_30
Prior P(Good) = 0.2879, P(Bad) = 0.7121
strong -> ask_delta: Good=-0.1087, Bad=-0.1701, ratio=0.5976
weak -> bid_delta: Good=-0.0888, Bad=-0.1106, ratio=0.1585
useless -> ask_std: Good=0.1258, Bad=0.1204, ratio=0.0524
useless -> bid_std: Good=0.1093, Bad=0.0967, ratio=0.1493
useless -> yes_dist: Good=-76.2389, Bad=-74.8289, ratio=0.0190
useless -> log_return: Good=-0.0004, Bad=-0.0003, ratio=0.0584
useless -> m3_log_return: Good=0.0004, Bad=0.0004, ratio=0.0082
useless -> m5_log_return: Good=0.0004, Bad=0.0004, ratio=0.0869
useless -> ma3_vs_strike: Good=-0.0745, Bad=-0.0741, ratio=0.0052
useless -> ma5_vs_strike: Good=-0.0616, Bad=-0.0575, ratio=0.0598
useless -> yes_dist_pct: Good=-0.0994, Bad=-0.0973, ratio=0.0223
useless -> m1_yes_dist_momentum: Good=-27.7168, Bad=-25.4662, ratio=0.0597
weak -> m3_yes_dist_momentum: Good=-33.4942, Bad=-43.6885, ratio=0.1911
useless -> m5_yes_dist_momentum: Good=-54.0837, Bad=-64.8785, ratio=0.1351
strong -> time_decay: Good=6.7368, Bad=4.8936, ratio=0.6160
useless -> hour: Good=12.0526, Bad=12.1277, ratio=0.0267
medium -> minute: Good=27.2105, Bad=34.6809, ratio=0.4698
strong -> yes_spread: Good=0.0097, Bad=0.0052, ratio=0.9355
useless -> volume_surge: Good=1.3474, Bad=1.3758, ratio=0.0583
medium -> rsi: Good=-212.5372, Bad=-49.4197, ratio=0.3261
useless -> macd: Good=-19.2358, Bad=-16.4929, ratio=0.1329
weak -> signal_line: Good=-17.5963, Bad=-14.3265, ratio=0.1711
Total Good Ratio is 5

Comb is 0.1, reached is reached_40
Prior P(Good) = 0.2424, P(Bad) = 0.7576
strong -> ask_delta: Good=-0.1090, Bad=-0.1664, ratio=0.5605
weak -> bid_delta: Good=-0.0854, Bad=-0.1104, ratio=0.1783
useless -> ask_std: Good=0.1130, Bad=0.1248, ratio=0.1215
useless -> bid_std: Good=0.0993, Bad=0.1006, ratio=0.0165
weak -> yes_dist: Good=-64.6694, Bad=-78.6158, ratio=0.1987
useless -> log_return: Good=-0.0003, Bad=-0.0004, ratio=0.1473
medium -> m3_log_return: Good=0.0003, Bad=0.0004, ratio=0.3042
medium -> m5_log_return: Good=0.0003, Bad=0.0004, ratio=0.3208
weak -> ma3_vs_strike: Good=-0.0603, Bad=-0.0786, ratio=0.2572
medium -> ma5_vs_strike: Good=-0.0444, Bad=-0.0633, ratio=0.3192
weak -> yes_dist_pct: Good=-0.0842, Bad=-0.1022, ratio=0.1978
useless -> m1_yes_dist_momentum: Good=-22.0238, Bad=-27.4230, ratio=0.1433
weak -> m3_yes_dist_momentum: Good=-33.7425, Bad=-42.9974, ratio=0.1770
useless -> m5_yes_dist_momentum: Good=-57.0588, Bad=-63.2788, ratio=0.0782
medium -> time_decay: Good=6.5000, Bad=5.0800, ratio=0.4797
weak -> hour: Good=12.4375, Bad=12.0000, ratio=0.1534
weak -> minute: Good=29.1250, Bad=33.6200, ratio=0.2774
strong -> yes_spread: Good=0.0104, Bad=0.0052, ratio=1.0584
weak -> volume_surge: Good=1.2930, Bad=1.3915, ratio=0.2036
useless -> rsi: Good=-62.9885, Bad=-107.0624, ratio=0.1145
useless -> macd: Good=-19.0308, Bad=-16.7231, ratio=0.1116
useless -> signal_line: Good=-17.1297, Bad=-14.6720, ratio=0.1295
Total Good Ratio is 6

Comb is 0.1, reached is reached_50
Prior P(Good) = 0.2273, P(Bad) = 0.7727
strong -> ask_delta: Good=-0.1115, Bad=-0.1645, ratio=0.5137
useless -> bid_delta: Good=-0.0891, Bad=-0.1088, ratio=0.1388
useless -> ask_std: Good=0.1176, Bad=0.1232, ratio=0.0573
useless -> bid_std: Good=0.1036, Bad=0.0993, ratio=0.0537
weak -> yes_dist: Good=-63.0247, Bad=-78.8261, ratio=0.2240
useless -> log_return: Good=-0.0003, Bad=-0.0003, ratio=0.0829
medium -> m3_log_return: Good=0.0003, Bad=0.0004, ratio=0.3078
medium -> m5_log_return: Good=0.0003, Bad=0.0004, ratio=0.3534
medium -> ma3_vs_strike: Good=-0.0575, Bad=-0.0791, ratio=0.3014
medium -> ma5_vs_strike: Good=-0.0421, Bad=-0.0636, ratio=0.3620
weak -> yes_dist_pct: Good=-0.0819, Bad=-0.1026, ratio=0.2252
useless -> m1_yes_dist_momentum: Good=-23.7880, Bad=-26.7982, ratio=0.0794
weak -> m3_yes_dist_momentum: Good=-32.2520, Bad=-43.2543, ratio=0.2104
useless -> m5_yes_dist_momentum: Good=-60.2113, Bad=-62.2296, ratio=0.0254
medium -> time_decay: Good=6.4667, Bad=5.1176, ratio=0.4500
weak -> hour: Good=12.6000, Bad=11.9608, ratio=0.2232
medium -> minute: Good=28.5333, Bad=33.7059, ratio=0.3171
strong -> yes_spread: Good=0.0107, Bad=0.0052, ratio=1.1098
useless -> volume_surge: Good=1.3211, Bad=1.3813, ratio=0.1238
weak -> rsi: Good=-32.4897, Bad=-115.1684, ratio=0.2251
useless -> macd: Good=-18.2315, Bad=-17.0034, ratio=0.0593
useless -> signal_line: Good=-16.2295, Bad=-14.9850, ratio=0.0658
Total Good Ratio is 8

Comb is 0.1, reached is reached_60
Prior P(Good) = 0.2121, P(Bad) = 0.7879
strong -> ask_delta: Good=-0.1111, Bad=-0.1636, ratio=0.5048
useless -> bid_delta: Good=-0.0941, Bad=-0.1071, ratio=0.0907
useless -> ask_std: Good=0.1211, Bad=0.1222, ratio=0.0102
useless -> bid_std: Good=0.1060, Bad=0.0988, ratio=0.0900
weak -> yes_dist: Good=-61.4264, Bad=-78.9525, ratio=0.2467
useless -> log_return: Good=-0.0003, Bad=-0.0003, ratio=0.0439
weak -> m3_log_return: Good=0.0003, Bad=0.0004, ratio=0.2143
medium -> m5_log_return: Good=0.0003, Bad=0.0004, ratio=0.4264
medium -> ma3_vs_strike: Good=-0.0544, Bad=-0.0795, ratio=0.3511
medium -> ma5_vs_strike: Good=-0.0392, Bad=-0.0640, ratio=0.4181
weak -> yes_dist_pct: Good=-0.0799, Bad=-0.1027, ratio=0.2476
useless -> m1_yes_dist_momentum: Good=-24.8907, Bad=-26.4435, ratio=0.0405
weak -> m3_yes_dist_momentum: Good=-32.8479, Bad=-42.8823, ratio=0.1908
useless -> m5_yes_dist_momentum: Good=-52.8586, Bad=-64.1704, ratio=0.1473
strong -> time_decay: Good=6.6429, Bad=5.0962, ratio=0.5160
weak -> hour: Good=12.7143, Bad=11.9423, ratio=0.2668
medium -> minute: Good=27.6429, Bad=33.8462, ratio=0.3792
strong -> yes_spread: Good=0.0111, Bad=0.0052, ratio=1.2262
useless -> volume_surge: Good=1.3445, Bad=1.3739, ratio=0.0596
weak -> rsi: Good=-34.8104, Bad=-112.9536, ratio=0.2123
useless -> macd: Good=-17.4025, Bad=-17.2502, ratio=0.0073
useless -> signal_line: Good=-15.3513, Bad=-15.2454, ratio=0.0056
Total Good Ratio is 7

Comb is 0.1, reached is reached_70
Prior P(Good) = 0.1970, P(Bad) = 0.8030
medium -> ask_delta: Good=-0.1165, Bad=-0.1613, ratio=0.4292
useless -> bid_delta: Good=-0.1021, Bad=-0.1049, ratio=0.0194
weak -> ask_std: Good=0.1099, Bad=0.1249, ratio=0.1531
weak -> bid_std: Good=0.1108, Bad=0.0977, ratio=0.1619
weak -> yes_dist: Good=-62.9354, Bad=-78.2517, ratio=0.2133
useless -> log_return: Good=-0.0003, Bad=-0.0003, ratio=0.0777
weak -> m3_log_return: Good=0.0003, Bad=0.0004, ratio=0.1738
medium -> m5_log_return: Good=0.0003, Bad=0.0004, ratio=0.3637
weak -> ma3_vs_strike: Good=-0.0573, Bad=-0.0783, ratio=0.2917
medium -> ma5_vs_strike: Good=-0.0426, Bad=-0.0627, ratio=0.3390
weak -> yes_dist_pct: Good=-0.0819, Bad=-0.1018, ratio=0.2132
useless -> m1_yes_dist_momentum: Good=-23.7546, Bad=-26.6928, ratio=0.0756
weak -> m3_yes_dist_momentum: Good=-31.0023, Bad=-43.1457, ratio=0.2304
weak -> m5_yes_dist_momentum: Good=-50.6762, Bad=-64.4923, ratio=0.1792
strong -> time_decay: Good=6.7692, Bad=5.0943, ratio=0.5542
weak -> hour: Good=12.6154, Bad=11.9811, ratio=0.2157
strong -> minute: Good=25.5385, Bad=34.2453, ratio=0.5547
strong -> yes_spread: Good=0.0105, Bad=0.0055, ratio=1.0162
weak -> volume_surge: Good=1.2727, Bad=1.3909, ratio=0.2514
weak -> rsi: Good=-37.4483, Bad=-110.8322, ratio=0.1988
useless -> macd: Good=-17.8271, Bad=-17.1489, ratio=0.0324
useless -> signal_line: Good=-15.9073, Bad=-15.1110, ratio=0.0419
Total Good Ratio is 6

Comb is 0.1, reached is reached_90
Prior P(Good) = 0.1818, P(Bad) = 0.8182
medium -> ask_delta: Good=-0.1188, Bad=-0.1599, ratio=0.3888
useless -> bid_delta: Good=-0.1006, Bad=-0.1052, ratio=0.0310
useless -> ask_std: Good=0.1140, Bad=0.1237, ratio=0.0979
weak -> bid_std: Good=0.1143, Bad=0.0972, ratio=0.2087
weak -> yes_dist: Good=-64.1200, Bad=-77.7048, ratio=0.1867
useless -> log_return: Good=-0.0003, Bad=-0.0003, ratio=0.0534
useless -> m3_log_return: Good=0.0004, Bad=0.0004, ratio=0.1090
weak -> m5_log_return: Good=0.0003, Bad=0.0004, ratio=0.2931
weak -> ma3_vs_strike: Good=-0.0584, Bad=-0.0777, ratio=0.2645
medium -> ma5_vs_strike: Good=-0.0433, Bad=-0.0621, ratio=0.3132
weak -> yes_dist_pct: Good=-0.0835, Bad=-0.1011, ratio=0.1865
useless -> m1_yes_dist_momentum: Good=-24.4492, Bad=-26.4841, ratio=0.0514
weak -> m3_yes_dist_momentum: Good=-31.9542, Bad=-42.7093, ratio=0.2023
weak -> m5_yes_dist_momentum: Good=-50.6842, Bad=-64.2346, ratio=0.1741
strong -> time_decay: Good=6.7500, Bad=5.1296, ratio=0.5262
useless -> hour: Good=12.3333, Bad=12.0556, ratio=0.0944
medium -> minute: Good=27.0000, Bad=33.7593, ratio=0.4320
strong -> yes_spread: Good=0.0107, Bad=0.0055, ratio=1.0312
weak -> volume_surge: Good=1.3025, Bad=1.3821, ratio=0.1680
weak -> rsi: Good=-39.1159, Bad=-109.1027, ratio=0.1887
useless -> macd: Good=-18.3659, Bad=-17.0418, ratio=0.0627
useless -> signal_line: Good=-16.4257, Bad=-15.0105, ratio=0.0738
Total Good Ratio is 5

Comb is 0.1, reached is reached_99
Prior P(Good) = 0.1667, P(Bad) = 0.8333
weak -> ask_delta: Good=-0.1267, Bad=-0.1576, ratio=0.2925
weak -> bid_delta: Good=-0.1306, Bad=-0.0991, ratio=0.2298
useless -> ask_std: Good=0.1211, Bad=0.1221, ratio=0.0103
weak -> bid_std: Good=0.1131, Bad=0.0978, ratio=0.1835
weak -> yes_dist: Good=-63.1327, Bad=-77.6553, ratio=0.1965
useless -> log_return: Good=-0.0003, Bad=-0.0003, ratio=0.0083
useless -> m3_log_return: Good=0.0004, Bad=0.0004, ratio=0.0195
weak -> m5_log_return: Good=0.0004, Bad=0.0004, ratio=0.2037
medium -> ma3_vs_strike: Good=-0.0550, Bad=-0.0780, ratio=0.3124
medium -> ma5_vs_strike: Good=-0.0384, Bad=-0.0628, ratio=0.4076
weak -> yes_dist_pct: Good=-0.0822, Bad=-0.1010, ratio=0.1962
useless -> m1_yes_dist_momentum: Good=-26.4527, Bad=-26.0464, ratio=0.0101

In [44]:
df_name = 0.10
df_result_name = 'reached_99'

df_results = pd.DataFrame(res[df_name])
df_results = df_results[df_results['hour'].isin(good_hours)]
df_expected = df_results[df_result_name]

# Separate good and bad outcomes
good = df_results[df_expected == 1]
bad = df_results[df_expected == 0]

# Prior probabilities
prior_good = len(good) / len(df_results)
prior_bad = len(bad) / len(df_results)
likelihoods = {}
params = {}

for col in feature_cols:
    good_mean, good_std = good[col].mean(), good[col].std()
    bad_mean, bad_std = bad[col].mean(), bad[col].std()
    
    likelihoods[col] = {
        'good': (good_mean, good_std),
        'bad': (bad_mean, bad_std),
    }
    
    # diff = good_mean - bad_mean
    ratio, grade = evaluate_feature(good_mean, good_std, bad_mean, bad_std)
    if grade == 'strong' or grade == 'medium':
        print(f"{grade} -> {col}: Good={good_mean:.4f}, Bad={bad_mean:.4f}, Ratio={ratio:.4f}")
        params[col] = {'good': (good_mean, good_std), 'bad': (bad_mean, bad_std),}
# for col in feature_cols:
#     g_mean, g_std = likelihoods[col]['good']
#     b_mean, b_std = likelihoods[col]['bad']
#     params[col] = {
#         'good': (g_mean, g_std),
#         'bad': (b_mean, b_std)
#     }
    
params['period'] = {
    'good': (prior_good,),
    'bad': (prior_bad,)
}
print(f"good is: {prior_good}, bad is: {prior_bad}")

medium -> ma3_vs_strike: Good=-0.0550, Bad=-0.0780, Ratio=0.3124
medium -> ma5_vs_strike: Good=-0.0384, Bad=-0.0628, Ratio=0.4076
medium -> time_decay: Good=6.7273, Bad=5.1636, Ratio=0.4969
strong -> minute: Good=24.6364, Bad=34.1091, Ratio=0.6437
strong -> yes_spread: Good=0.0107, Bad=0.0056, Ratio=0.9992
good is: 0.16666666666666666, bad is: 0.8333333333333334

In [45]:
# type 1 and 2 errors

type1 = 0 
type2 = 0  

total_good = 0
total_bad = 0

feature_names = [name for name in params.keys() if name != 'period']
def predict(*args):
    # Start from prior odds
    log_odds = np.log(params['period']['good'][0] / params['period']['bad'][0])
    
    for name, x in zip(feature_names, args):
        g_m, g_s = params[name]['good']
        b_m, b_s = params[name]['bad']
        
        # Likelihood ratio
        p_g = norm.pdf(x, g_m, g_s + 1e-10)
        p_b = norm.pdf(x, b_m, b_s + 1e-10)
        
        if p_b > 0:
            log_odds += np.log(p_g / p_b)
    
    prob = 1 / (1 + np.exp(-log_odds))
    return prob

for threshold in [0.1, 0.15, 0.2, 0.25, 0.30, 0.35, 0.40, 0.45]:
    type1, type2 = 0, 0
    total_good, total_bad = 0, 0
    
    for index, row in df_results.iterrows(): 
        p = predict(*(row[x] for x in params if x != 'period')) 
        
        actual = row[df_result_name]
        
        if actual == 1:
            total_good += 1
            if p < threshold:
                type1 += 1
        if actual == 0:
            total_bad += 1
            if p >= threshold:
                type2 += 1
    
    bought_good = total_good - type1
    bought_bad = type2
    
    type1_rate = type1 / total_good
    type2_rate = type2 / total_bad
    
    # Precision & Recall
    precision = bought_good / (bought_good + bought_bad) if (bought_good + bought_bad) > 0 else 0
    recall = 1 - type1_rate
    
    # F1
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
    
    print(f"Threshold={threshold:.2f}: Type1={type1_rate:.2f}, Type2={type2_rate:.2f}, F1={f1:.4f}, Precision={precision:.4f}, Recall={recall:.4f}")

Threshold=0.10: Type1=0.09, Type2=0.35, F1=0.5000, Precision=0.3448, Recall=0.9091
Threshold=0.15: Type1=0.09, Type2=0.25, F1=0.5714, Precision=0.4167, Recall=0.9091
Threshold=0.20: Type1=0.27, Type2=0.18, F1=0.5517, Precision=0.4444, Recall=0.7273
Threshold=0.25: Type1=0.45, Type2=0.15, F1=0.4800, Precision=0.4286, Recall=0.5455
Threshold=0.30: Type1=0.45, Type2=0.13, F1=0.5000, Precision=0.4615, Recall=0.5455
Threshold=0.35: Type1=0.55, Type2=0.13, F1=0.4348, Precision=0.4167, Recall=0.4545
Threshold=0.40: Type1=0.55, Type2=0.11, F1=0.4545, Precision=0.4545, Recall=0.4545
Threshold=0.45: Type1=0.64, Type2=0.09, F1=0.4000, Precision=0.4444, Recall=0.3636

In [42]:
# export model

def write_model_to_json(parameters: dict, filepath: str = None):
    if filepath is None:
        filepath = MODEL_PATH / 'yes_bayesian.json'
    
    params_serializable = {}
    for feature, values in parameters.items():
        params_serializable[feature] = {
            'good': list(values['good']),
            'bad': list(values['bad'])
        }
    
    with open(filepath, 'w') as f:
        json.dump(params_serializable, f, indent=2)
    
    print(f"Model saved to {filepath}")


def load_model_from_json(filepath: str = None):
    if filepath is None:
        filepath = MODEL_PATH / 'yes_bayesian.json'
    
    with open(filepath, 'r') as f:
        params_serializable = json.load(f)
    
    # Convert lists back to tuples
    parameters = {}
    for feature, values in params_serializable.items():
        parameters[feature] = {
            'good': tuple(values['good']),
            'bad': tuple(values['bad'])
        }
    
    return parameters


# Correct dict syntax
# params = {
#     'period': {
#         'good': (0.4138,),
#         'bad': (0.5862,)
#     },
#     'm1_yes_dist_momentum': {
#         'good': (-17.5070, 51.8947),
#         'bad':  (-19.7738, 48.4898)
#     },
#     'm3_yes_dist_momentum': {
#         'good': (-29.0380, 82.5982),
#         'bad':  (-32.8337, 73.5574)
#     },
#     'm5_yes_dist_momentum': {
#         'good': (-31.1500, 93.6206),
#         'bad':  (-37.5775, 85.6289)
#     },
#     'yes_dist': {
#         'good': (-19.9004, 29.5222),
#         'bad':  (-22.8592, 38.3313)
#     },
# }

# Write
write_model_to_json(params)
print(params)

Model saved to /Users/yingxie/Documents/Git/Quant/Kalshi/btc_15_strategy/models/yes_bayesian.json
{'ma3_vs_strike': {'good': (-0.05502554991346866, 0.06534699062030032), 'bad': (-0.07801920120532012, 0.08186435722357918)}, 'ma5_vs_strike': {'good': (-0.038416123009839785, 0.052047553036145194), 'bad': (-0.06277846438433961, 0.06749388402790055)}, 'time_decay': {'good': (6.7272727272727275, 3.2891004572955533), 'bad': (5.163636363636364, 3.004710107195506)}, 'minute': {'good': (24.636363636363637, 12.745765785332221), 'bad': (34.10909090909091, 16.686291476308426)}, 'yes_spread': {'good': (0.010727272727272731, 0.005968097001405209), 'bad': (0.005618181818181821, 0.0042578507406076304)}, 'period': {'good': (0.16666666666666666,), 'bad': (0.8333333333333334,)}}

In [32]:
# hour research
reached_list = [50,60,70,90,99]
time_dict = {str(x): 0 for x in range(24)}
test_df = comb_10
test_entry_price = 10

for hour in range(24):
    for reached in reached_list:
        df_h = test_df[test_df['hour'] == hour]
        # if len(df_h) < 2:
        #     continue
        rate = df_h['reached_' + str(reached)].mean()
        ev = rate * ((reached - test_entry_price) / 100)  - (1-rate) * test_entry_price / 100
        time_dict[str(hour)] += ev

sorted_items = sorted(time_dict.items(), key=lambda x: int(x[0]), reverse=True)
for key, item in sorted_items:
    print(f"Hour: {key}, EV: {item:.3f}")

Hour: 23, EV: nan
Hour: 22, EV: nan
Hour: 21, EV: nan
Hour: 20, EV: 1.345
Hour: 19, EV: -0.500
Hour: 18, EV: -0.500
Hour: 17, EV: -0.300
Hour: 16, EV: 0.186
Hour: 15, EV: 0.175
Hour: 14, EV: -0.225
Hour: 13, EV: -0.500
Hour: 12, EV: 1.609
Hour: 11, EV: 0.024
Hour: 10, EV: 0.238
Hour: 9, EV: 0.027
Hour: 8, EV: -0.400
Hour: 7, EV: 0.607
Hour: 6, EV: -0.165
Hour: 5, EV: 0.024
Hour: 4, EV: -0.026
Hour: 3, EV: -0.269
Hour: 2, EV: 0.145
Hour: 1, EV: nan
Hour: 0, EV: nan

In [33]:
# start research
trade_hour = [x for x in range(23)]
reached_dict = {str(x): 0 for x in reached_list}
for hour in trade_hour:
    for reached in reached_list:
        df_h = test_df[test_df['hour'] == hour]
        if len(df_h) < 5:
            continue
        rate = df_h['reached_' + str(reached)].mean()
        ev = rate * ((reached - test_entry_price)/100 - 0.1)  - (1-rate) * test_entry_price / 100
        reached_dict[str(reached)] += ev

for key, item in reached_dict.items():
    print(f"Reached: {key}, EV: {item:.3f}")

Reached: 50, EV: -0.240
Reached: 60, EV: -0.171
Reached: 70, EV: -0.018
Reached: 90, EV: 0.151
Reached: 99, EV: 0.325

In [37]:
# final hour research
trade_hour = [x for x in range(23)]
for hour in trade_hour:
    df_h = test_df[test_df['hour'] == hour]
    # if len(df_h) < 2:
    #     continue
    rate = df_h['reached_99'].mean()
    ev = rate * (0.99 - 0.1)  - (1-rate) * 0.10
    print(f"{hour:02d}:00 {len(df_h):3d} trades win {rate:.0%} | EV {ev:.2f}")

00:00   0 trades win nan% | EV nan
01:00   0 trades win nan% | EV nan
02:00  15 trades win 13% | EV 0.03
03:00  16 trades win 6% | EV -0.04
04:00  16 trades win 6% | EV -0.04
05:00  16 trades win 12% | EV 0.02
06:00  11 trades win 9% | EV -0.01
07:00  10 trades win 30% | EV 0.20
08:00  11 trades win 0% | EV -0.10
09:00  14 trades win 14% | EV 0.04
10:00  10 trades win 20% | EV 0.10
11:00   8 trades win 12% | EV 0.02
12:00   7 trades win 57% | EV 0.47
13:00   9 trades win 0% | EV -0.10
14:00   4 trades win 0% | EV -0.10
15:00   4 trades win 0% | EV -0.10
16:00   8 trades win 12% | EV 0.02
17:00   9 trades win 0% | EV -0.10
18:00   1 trades win 0% | EV -0.10
19:00   3 trades win 0% | EV -0.10
20:00   2 trades win 50% | EV 0.40
21:00   0 trades win nan% | EV nan
22:00   0 trades win nan% | EV nan